baseURL: http://something-fresh.org/
languageCode: en-us
title: Krzyżówki
theme: hugo-fresh-2
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
    # Logo (from static/images/logos/___)
    image: logos/logo.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 112
    # height: 28
  font:
    name: "Open Sans"
    sizes: [400, 600]
  hero:
    # Main hero title
    title: Krzyżówki.
    # Hero subtitle (optional)
    subtitle: Najlepsze krzyżówki zawsze pod ręką!
    # Hero image (from static/images/___)
    image: illustrations/crossword-mockup-nobg.png

    playimage: logos/google-play-badge.png
    playlink: https://play.google.com/store/apps/details?id=com.datumai.mobile.crossword.flutter_crossword
    appimage: logos/app-store-badge.svg
    appLink: https://apps.apple.com/us/app/krzy%C5%BC%C3%B3wki/id1642158887
  navbar:
    - title: Privacy Policy
      url: /privacy-policy
    - title: Contact
      url: mailto:spaleniak.weronika@gmail.com?subject=subject&cc=cc@example.com
